[package]
name = "datalove-repl"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
bct.workspace = true
salsa.workspace = true
datalove-datalit.path = "../datalove-datalit"
datalove-datafun.path = "../datalove-datafun"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
web-sys = { version = "0.3", features = ["console", "Worker", "WorkerOptions", "WorkerType", "MessageEvent", "ErrorEvent", "DedicatedWorkerGlobalScope"] }
js-sys = "0.3"

[dev-dependencies]
termcolor = "1.4"

[[test]]
name = "engine_tests"
harness = false
