[package]
name = "datalove-repl"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
bct.workspace = true
datalove-datalit.path = "../datalove-datalit"
datalove-datafun.path = "../datalove-datafun"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
termcolor = "1.4"

[[test]]
name = "repl_tests"
path = "tests/repl_tests.rs"
harness = false
