[package]
name = "datalove"
description = "The datalove language."
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bct.workspace = true
datalove-datalit.workspace = true
datalove-datafun.workspace = true
datalove-datafun-ast.workspace = true
datalove-datafun-ir.workspace = true
datalove-datafun-interp.workspace = true
datalove-datafun-cranelift-jit.workspace = true
datalove-datafun-pkg.workspace = true
datalove-datafun-sema.workspace = true
datalove-diagnostic.workspace = true
datalove-paths.workspace = true
datalove-repl.workspace = true
datalove-rt.workspace = true
datalove-sys-packages.workspace = true
