[package]
name = "datalove-datalit"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
bct.workspace = true
salsa.workspace = true
serde = { version = "1", features = ["derive"] }
datalove-rtdt.path = "../datalove-rtdt"
datalove-rt.path = "../datalove-rt"

[dev-dependencies]
datalove-exampletest.path = "../datalove-exampletest"

[[test]]
name = "parser_tests"
path = "tests/parser_tests.rs"
harness = false

[[test]]
name = "resolve_tests"
path = "tests/resolve_tests.rs"
harness = false

[[test]]
name = "tycheck_tests"
path = "tests/tycheck_tests.rs"
harness = false

[[test]]
name = "pretty_tests"
path = "tests/pretty_tests.rs"
harness = false

[[test]]
name = "roundtrip_tests"
path = "tests/roundtrip_tests.rs"
harness = false
