[workspace.package]
description = "todo"
version = "0.1.0"
license = "Apache-2.0 OR MIT"
authors = ["Brian Anderson <andersrb@gmail.com>"]
documentation = "todo"
edition = "2024"

[workspace]
resolver = "2"

members = [
  "crates/*",
]

exclude = [
  "crates/datalove-repl-worker",
  "crates/datalove-repl-egui",
  "crates/datalove-web",
]

default-members = [
  "crates/datalove-cli",
]

[workspace.dependencies]
rmx.package = "rustmax"
rmx.version = "0.0.7"
rmx.features = [
  "rmx-profile-wasm",
  "comrak",
  "tera",
]
bct.package = "bcts"
bct.path = "crates/bcts"
serde.version = "1"
memchr.version = "2"
enum-iterator.version = "2"
salsa.version = "0.25.2"
rayon.version = "1.11"

[profile.release]
overflow-checks = true
