[workspace.package]
description = "todo"
version = "0.1.0"
license = "Apache-2.0 OR MIT"
authors = ["Brian Anderson <andersrb@gmail.com>"]
documentation = "todo"
edition = "2024"

[workspace]
resolver = "2"

members = [
  "crates/*",
]

exclude = [
  "sys/std/rider",
]

default-members = [
  "crates/datalove-cli",
]

[workspace.dependencies]
rmx.package = "rustmax"
rmx.version = "0.0.8"
rmx.features = [
  "rmx-profile-wasm",
  "comrak",
  "tera",
  "termcolor",
]
bct.package = "bcts"
bct.path = "crates/bcts"
serde.version = "1"
enum-iterator.version = "2"
salsa.version = "0.25.2"

[profile.dev]
debug = 1

[profile.release]
overflow-checks = true
lto = "thin"
codegen-units = 1
opt-level = "s"

