; this is an example of the data language.
; there is also a code language.
; ctor syntax needs to have unambiguous type.
; values need to have specified binary runtime representation
;
; prefixes:
; - `@` - built-in types
; - `#` - built-in expressions
; - `%` - statement

; example, with type hint (":  /")
: [
  (@u32, @bool),
] / [
  (1, #true),
  (2, #true),
]


; primitive types

: @nil / #nil
: @bool / #true
: @bool / #false
: @u32 / 1
: @string / "abc"


; list
: [@u32] / [1, 2, 3]
; array
;let v: [@u32 * _] = [1, 2, 3]

; tuple
: (@bool, @u32) / (#true, 1)
: (@u32) / (1)
: () / ()

; anonymous struct
; like js object, python dict
: {
  field1: @bool,
  field2: @u32,
  field3: @u32,
} / {
  field1 = #true,
  field2: @u32 = 1,
  field3 = : @u32 / 2,
}

; named struct
%struct Foo {
  field1: @bool,
}

: @struct Foo / #struct Foo {
  field1 = #true,
}

; named tuple
%tuple Bar (@bool, @u32)

: @tuple Bar / #tuple Bar (#true, 1)


; anonymous enum
: @enum {
  Foo,
  Bar @u32,
  Baz (@bool, @u32),
} / #enum | Foo

: @enum {
  Foo,
  Bar @u32,
  Baz (@bool, @u32),
} / #enum | Bar 2

: @enum {
  Foo,
  Bar @u32,
  Baz (@bool, @u32),
} / #enum | Bar (#true, 1)

; named enum
%enum Quux {
  Foo,
  Bar @u32,
  Baz (@bool, @u32),
}

: @enum Quux / #enum Quux | Bar (#true, 1)

: @enum Quux / #enum | Bar (#true, 1)

; map

; set

; optional
: ?@u32 = 


; todo?
;
; - bitset
; - table (polars)
; - graph
; - array
; - multi-dimensional array
; - range (python)?
; - complex
; - real
