[package]
name = "datalove-repl-rat"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
datalove-repl.path = "../datalove-repl"
ratatui = { version = "0.29", features = ["crossterm"] }
crossterm = "0.28"
tui-textarea = "0.7"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
