[package]
name = "datalove-repl-rat"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
datalove-repl.path = "../datalove-repl"
ratatui = { version = "0.30", features = ["crossterm"] }
crossterm = "0.29"
tui-textarea.package = "tui-textarea-2"
tui-textarea.version = "0.13"
