[package]
name = "datalove-datafun-sema"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[features]
index-64 = ["datalove-datafun-ir/index-64", "datalove-datafun-common/index-64"]

[dependencies]
rmx.workspace = true
salsa.workspace = true
datalove-datafun-ast.path = "../datalove-datafun-ast"
datalove-datafun-common.path = "../datalove-datafun-common"
datalove-datafun-ir.path = "../datalove-datafun-ir"
