[package]
name = "datalove-datafun-sema"
description = "Semantic types shared by ownership analysis and lowering."
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[features]
index-64 = ["datalove-datafun-ir/index-64", "datalove-datafun-common/index-64"]

[dependencies]
rmx.workspace = true
salsa.workspace = true
bct.workspace = true
datalove-datafun-ast.workspace = true
datalove-datafun-common.workspace = true
datalove-datalit.workspace = true
datalove-datafun-ir.workspace = true
