[package]
name = "datalove-datafun-ir"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
ron = "0.8"
salsa.workspace = true
datalove-datafun-intrinsics.path = "../datalove-datafun-intrinsics"
datalove-datalit.path = "../datalove-datalit"
