//! Every exported function must match its declaration in `datalove-rti`.
//!
//! Generated by `scripts/gen-rti.py`. A rider is built against the
//! declarations and run against these definitions, so the two disagreeing is a
//! rider calling a function whose arguments are not what it passed. Nothing
//! about the symbol name says so, which is why it is checked here instead.
//!
//! Each line puts the definition and the declaration in one array, which makes
//! the compiler coerce both to a single function pointer type and reject the
//! pair if their signatures differ.

const _: () = {
    let _ = [crate::c::dtlv_rti_init, datalove_rti::decl::dtlv_rti_init];
    let _ = [crate::c::dtlv_rti_shutdown, datalove_rti::decl::dtlv_rti_shutdown];
    let _ = [crate::c::dtlv_rti_mem_alloc_local, datalove_rti::decl::dtlv_rti_mem_alloc_local];
    let _ = [crate::c::dtlv_rti_mem_alloc_raw_local, datalove_rti::decl::dtlv_rti_mem_alloc_raw_local];
    let _ = [crate::c::dtlv_rti_mem_free_raw_local, datalove_rti::decl::dtlv_rti_mem_free_raw_local];
    let _ = [crate::c::dtlv_rti_mem_free_local, datalove_rti::decl::dtlv_rti_mem_free_local];
    let _ = [crate::c::dtlv_rti_move_value_local, datalove_rti::decl::dtlv_rti_move_value_local];
    let _ = [crate::c::dtlv_rti_clone_local, datalove_rti::decl::dtlv_rti_clone_local];
    let _ = [crate::c::dtlv_rti_eq_local, datalove_rti::decl::dtlv_rti_eq_local];
    let _ = [crate::c::dtlv_rti_eq_unique_local, datalove_rti::decl::dtlv_rti_eq_unique_local];
    let _ = [crate::c::dtlv_rti_cmp_local, datalove_rti::decl::dtlv_rti_cmp_local];
    let _ = [crate::c::dtlv_rti_cmp_total_local, datalove_rti::decl::dtlv_rti_cmp_total_local];
    let _ = [crate::c::dtlv_rti_int_add, datalove_rti::decl::dtlv_rti_int_add];
    let _ = [crate::c::dtlv_rti_int_sub, datalove_rti::decl::dtlv_rti_int_sub];
    let _ = [crate::c::dtlv_rti_int_mul, datalove_rti::decl::dtlv_rti_int_mul];
    let _ = [crate::c::dtlv_rti_int_neg, datalove_rti::decl::dtlv_rti_int_neg];
    let _ = [crate::c::dtlv_rti_int_div_checked, datalove_rti::decl::dtlv_rti_int_div_checked];
    let _ = [crate::c::dtlv_rti_int_from_fixed, datalove_rti::decl::dtlv_rti_int_from_fixed];
    let _ = [crate::c::dtlv_rti_int_from_limbs, datalove_rti::decl::dtlv_rti_int_from_limbs];
    let _ = [crate::c::dtlv_rti_any_destroy_local, datalove_rti::decl::dtlv_rti_any_destroy_local];
    let _ = [crate::c::dtlv_rti_error_from_local, datalove_rti::decl::dtlv_rti_error_from_local];
    let _ = [crate::c::dtlv_rti_data_from_local, datalove_rti::decl::dtlv_rti_data_from_local];
    let _ = [crate::c::dtlv_rti_clone_erased_local, datalove_rti::decl::dtlv_rti_clone_erased_local];
    let _ = [crate::c::dtlv_rti_dyn_binop, datalove_rti::decl::dtlv_rti_dyn_binop];
    let _ = [crate::c::dtlv_rti_dyn_binop_checked, datalove_rti::decl::dtlv_rti_dyn_binop_checked];
    let _ = [crate::c::dtlv_rti_dyn_unop, datalove_rti::decl::dtlv_rti_dyn_unop];
    let _ = [crate::c::dtlv_rti_dyn_const, datalove_rti::decl::dtlv_rti_dyn_const];
    let _ = [crate::c::dtlv_rti_dyn_float_const, datalove_rti::decl::dtlv_rti_dyn_float_const];
    let _ = [crate::c::dtlv_rti_dyn_neg_checked, datalove_rti::decl::dtlv_rti_dyn_neg_checked];
    let _ = [crate::c::dtlv_rti_data_parts, datalove_rti::decl::dtlv_rti_data_parts];
    let _ = [crate::c::dtlv_rti_data_borrow, datalove_rti::decl::dtlv_rti_data_borrow];
    let _ = [crate::c::dtlv_rti_data_into_local, datalove_rti::decl::dtlv_rti_data_into_local];
    let _ = [crate::c::dtlv_rti_erase_local, datalove_rti::decl::dtlv_rti_erase_local];
    let _ = [crate::c::dtlv_rti_reify_local, datalove_rti::decl::dtlv_rti_reify_local];
    let _ = [crate::c::dtlv_rti_string_create_local, datalove_rti::decl::dtlv_rti_string_create_local];
    let _ = [crate::c::dtlv_rti_string_destroy_local, datalove_rti::decl::dtlv_rti_string_destroy_local];
    let _ = [crate::c::dtlv_rti_string_push_bytes_local, datalove_rti::decl::dtlv_rti_string_push_bytes_local];
    let _ = [crate::c::dtlv_rti_string_clear_local, datalove_rti::decl::dtlv_rti_string_clear_local];
    let _ = [crate::c::dtlv_rti_string_from_bytes, datalove_rti::decl::dtlv_rti_string_from_bytes];
    let _ = [crate::c::dtlv_rti_pretty_print_local, datalove_rti::decl::dtlv_rti_pretty_print_local];
    let _ = [crate::c::dtlv_rti_btreemap_create_local, datalove_rti::decl::dtlv_rti_btreemap_create_local];
    let _ = [crate::c::dtlv_rti_btreemap_clone_from_slice_local, datalove_rti::decl::dtlv_rti_btreemap_clone_from_slice_local];
    let _ = [crate::c::dtlv_rti_btreemap_build_from_sorted_slices_local, datalove_rti::decl::dtlv_rti_btreemap_build_from_sorted_slices_local];
    let _ = [crate::c::dtlv_rti_btreemap_destroy_local, datalove_rti::decl::dtlv_rti_btreemap_destroy_local];
    let _ = [crate::c::dtlv_rti_btreemap_insert_local, datalove_rti::decl::dtlv_rti_btreemap_insert_local];
    let _ = [crate::c::dtlv_rti_btreemap_remove_local, datalove_rti::decl::dtlv_rti_btreemap_remove_local];
    let _ = [crate::c::dtlv_rti_btreemap_key_at_local, datalove_rti::decl::dtlv_rti_btreemap_key_at_local];
    let _ = [crate::c::dtlv_rti_btreemap_value_at_local, datalove_rti::decl::dtlv_rti_btreemap_value_at_local];
    let _ = [crate::c::dtlv_rti_btreeset_get_at_local, datalove_rti::decl::dtlv_rti_btreeset_get_at_local];
    let _ = [crate::c::dtlv_rti_btreemap_get_local, datalove_rti::decl::dtlv_rti_btreemap_get_local];
    let _ = [crate::c::dtlv_rti_btreemap_get_as_data_local, datalove_rti::decl::dtlv_rti_btreemap_get_as_data_local];
    let _ = [crate::c::dtlv_rti_list_push_erased_local, datalove_rti::decl::dtlv_rti_list_push_erased_local];
    let _ = [crate::c::dtlv_rti_element_write_local, datalove_rti::decl::dtlv_rti_element_write_local];
    let _ = [crate::c::dtlv_rti_btreemap_set_value_erased_local, datalove_rti::decl::dtlv_rti_btreemap_set_value_erased_local];
    let _ = [crate::c::dtlv_rti_list_remove_erased_local, datalove_rti::decl::dtlv_rti_list_remove_erased_local];
    let _ = [crate::c::dtlv_rti_list_pop_erased_local, datalove_rti::decl::dtlv_rti_list_pop_erased_local];
    let _ = [crate::c::dtlv_rti_list_set_erased_local, datalove_rti::decl::dtlv_rti_list_set_erased_local];
    let _ = [crate::c::dtlv_rti_list_insert_erased_local, datalove_rti::decl::dtlv_rti_list_insert_erased_local];
    let _ = [crate::c::dtlv_rti_btreeset_insert_erased_local, datalove_rti::decl::dtlv_rti_btreeset_insert_erased_local];
    let _ = [crate::c::dtlv_rti_btreemap_insert_erased_local, datalove_rti::decl::dtlv_rti_btreemap_insert_erased_local];
    let _ = [crate::c::dtlv_rti_btreemap_insert_data_local, datalove_rti::decl::dtlv_rti_btreemap_insert_data_local];
    let _ = [crate::c::dtlv_rti_btreeset_insert_data_local, datalove_rti::decl::dtlv_rti_btreeset_insert_data_local];
    let _ = [crate::c::dtlv_rti_btreemap_len_local, datalove_rti::decl::dtlv_rti_btreemap_len_local];
    let _ = [crate::c::dtlv_rti_btreeset_len_local, datalove_rti::decl::dtlv_rti_btreeset_len_local];
    let _ = [crate::c::dtlv_rti_btreemap_clear_local, datalove_rti::decl::dtlv_rti_btreemap_clear_local];
    let _ = [crate::c::dtlv_rti_btreemap_contains_key_local, datalove_rti::decl::dtlv_rti_btreemap_contains_key_local];
    let _ = [crate::c::dtlv_rti_btreemap_get_value_ref_local, datalove_rti::decl::dtlv_rti_btreemap_get_value_ref_local];
    let _ = [crate::c::dtlv_rti_btreemap_set_value_local, datalove_rti::decl::dtlv_rti_btreemap_set_value_local];
    let _ = [crate::c::dtlv_rti_btreeset_create_local, datalove_rti::decl::dtlv_rti_btreeset_create_local];
    let _ = [crate::c::dtlv_rti_btreeset_destroy_local, datalove_rti::decl::dtlv_rti_btreeset_destroy_local];
    let _ = [crate::c::dtlv_rti_btreeset_insert_local, datalove_rti::decl::dtlv_rti_btreeset_insert_local];
    let _ = [crate::c::dtlv_rti_btreeset_remove_local, datalove_rti::decl::dtlv_rti_btreeset_remove_local];
    let _ = [crate::c::dtlv_rti_btreeset_contains_local, datalove_rti::decl::dtlv_rti_btreeset_contains_local];
    let _ = [crate::c::dtlv_rti_btreeset_clear_local, datalove_rti::decl::dtlv_rti_btreeset_clear_local];
    let _ = [crate::c::dtlv_rti_btreeset_clone_from_slice_local, datalove_rti::decl::dtlv_rti_btreeset_clone_from_slice_local];
    let _ = [crate::c::dtlv_rti_btreeset_build_from_sorted_slice_local, datalove_rti::decl::dtlv_rti_btreeset_build_from_sorted_slice_local];
    let _ = [crate::c::dtlv_rti_list_create_local, datalove_rti::decl::dtlv_rti_list_create_local];
    let _ = [crate::c::dtlv_rti_list_create_from_slice_local, datalove_rti::decl::dtlv_rti_list_create_from_slice_local];
    let _ = [crate::c::dtlv_rti_list_build_from_slice_local, datalove_rti::decl::dtlv_rti_list_build_from_slice_local];
    let _ = [crate::c::dtlv_rti_list_destroy_local, datalove_rti::decl::dtlv_rti_list_destroy_local];
    let _ = [crate::c::dtlv_rti_list_clear_local, datalove_rti::decl::dtlv_rti_list_clear_local];
    let _ = [crate::c::dtlv_rti_list_set_data_local, datalove_rti::decl::dtlv_rti_list_set_data_local];
    let _ = [crate::c::dtlv_rti_list_insert_data_local, datalove_rti::decl::dtlv_rti_list_insert_data_local];
    let _ = [crate::c::dtlv_rti_list_remove_as_data_local, datalove_rti::decl::dtlv_rti_list_remove_as_data_local];
    let _ = [crate::c::dtlv_rti_list_len_local, datalove_rti::decl::dtlv_rti_list_len_local];
    let _ = [crate::c::dtlv_rti_list_get_as_data_local, datalove_rti::decl::dtlv_rti_list_get_as_data_local];
    let _ = [crate::c::dtlv_rti_list_pop_as_data_local, datalove_rti::decl::dtlv_rti_list_pop_as_data_local];
    let _ = [crate::c::dtlv_rti_list_push_data_local, datalove_rti::decl::dtlv_rti_list_push_data_local];
    let _ = [crate::c::dtlv_rti_list_get_erased_local, datalove_rti::decl::dtlv_rti_list_get_erased_local];
    let _ = [crate::c::dtlv_rti_list_get_local, datalove_rti::decl::dtlv_rti_list_get_local];
    let _ = [crate::c::dtlv_rti_list_set_local, datalove_rti::decl::dtlv_rti_list_set_local];
    let _ = [crate::c::dtlv_rti_list_push_local, datalove_rti::decl::dtlv_rti_list_push_local];
    let _ = [crate::c::dtlv_rti_list_pop_local, datalove_rti::decl::dtlv_rti_list_pop_local];
    let _ = [crate::c::dtlv_rti_list_insert_local, datalove_rti::decl::dtlv_rti_list_insert_local];
    let _ = [crate::c::dtlv_rti_list_remove_local, datalove_rti::decl::dtlv_rti_list_remove_local];
    let _ = [crate::c::dtlv_rti_list_reserve_local, datalove_rti::decl::dtlv_rti_list_reserve_local];
    let _ = [crate::c::dtlv_rti_list_shrink_to_fit_local, datalove_rti::decl::dtlv_rti_list_shrink_to_fit_local];
    let _ = [crate::c::dtlv_rti_list_extend_from_slice_local, datalove_rti::decl::dtlv_rti_list_extend_from_slice_local];
    let _ = [crate::c::dtlv_rti_tensor_create_from_slice_local, datalove_rti::decl::dtlv_rti_tensor_create_from_slice_local];
    let _ = [crate::c::dtlv_rti_tensor_destroy_local, datalove_rti::decl::dtlv_rti_tensor_destroy_local];
    let _ = [crate::c::dtlv_rti_tensor_get_local, datalove_rti::decl::dtlv_rti_tensor_get_local];
    let _ = [crate::c::dtlv_rti_tensor_set_local, datalove_rti::decl::dtlv_rti_tensor_set_local];
    let _ = [crate::c::dtlv_rti_tensor_transpose_local, datalove_rti::decl::dtlv_rti_tensor_transpose_local];
    let _ = [crate::c::dtlv_rti_tensor_slice_local, datalove_rti::decl::dtlv_rti_tensor_slice_local];
    let _ = [crate::c::dtlv_rti_tensor_reshape_local, datalove_rti::decl::dtlv_rti_tensor_reshape_local];
    let _ = [crate::c::dtlv_rti_tensor_init_local, datalove_rti::decl::dtlv_rti_tensor_init_local];
    let _ = [crate::c::dtlv_rti_tensor_hyperplane_clone_local, datalove_rti::decl::dtlv_rti_tensor_hyperplane_clone_local];
    let _ = [crate::c::dtlv_rti_table_create_local, datalove_rti::decl::dtlv_rti_table_create_local];
    let _ = [crate::c::dtlv_rti_table_destroy_local, datalove_rti::decl::dtlv_rti_table_destroy_local];
    let _ = [crate::c::dtlv_rti_table_push_row_local, datalove_rti::decl::dtlv_rti_table_push_row_local];
    let _ = [crate::c::dtlv_rti_table_build_from_rows_local, datalove_rti::decl::dtlv_rti_table_build_from_rows_local];
    let _ = [crate::c::dtlv_rti_table_get_local, datalove_rti::decl::dtlv_rti_table_get_local];
    let _ = [crate::c::dtlv_rti_table_set_local, datalove_rti::decl::dtlv_rti_table_set_local];
    let _ = [crate::c::dtlv_rti_table_clear_local, datalove_rti::decl::dtlv_rti_table_clear_local];
    let _ = [crate::c::dtlv_rti_table_len, datalove_rti::decl::dtlv_rti_table_len];
    let _ = [crate::c::dtlv_rti_set_debug_mode, datalove_rti::decl::dtlv_rti_set_debug_mode];
    let _ = [crate::c::dtlv_rti_debuglog_local, datalove_rti::decl::dtlv_rti_debuglog_local];
    let _ = [crate::c::dtlv_rti_get_debug_buffer, datalove_rti::decl::dtlv_rti_get_debug_buffer];
    let _ = [crate::c::dtlv_rti_clear_debug_buffer, datalove_rti::decl::dtlv_rti_clear_debug_buffer];
    let _ = [crate::c::dtlv_rti_field_offset, datalove_rti::decl::dtlv_rti_field_offset];
    let _ = [crate::c::dtlv_rti_field_tydesc, datalove_rti::decl::dtlv_rti_field_tydesc];
    let _ = [crate::c::dtlv_rti_field_read_local, datalove_rti::decl::dtlv_rti_field_read_local];
    let _ = [crate::c::dtlv_rti_element_tydesc, datalove_rti::decl::dtlv_rti_element_tydesc];
    let _ = [crate::c::dtlv_rti_btreemap_contains_key_erased_local, datalove_rti::decl::dtlv_rti_btreemap_contains_key_erased_local];
    let _ = [crate::c::dtlv_rti_btreemap_get_value_ref_erased_local, datalove_rti::decl::dtlv_rti_btreemap_get_value_ref_erased_local];
};

/// The declarations must cover every export, not merely agree with the ones
/// they name. `EXPORTED` is generated from the same scan as the lines above.
const _: () = assert!(
    datalove_rti::decl::EXPORTED == 125,
    "datalove-rti declares a different number of functions than datalove-rt exports",
);
