[package]
name = "datalove-datafun"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
bct.workspace = true
salsa.workspace = true
serde = { version = "1", features = ["derive"] }
datalove-datalit.path = "../datalove-datalit"

[dev-dependencies]
termcolor = "1.4.1"
