[package]
name = "datalove-datafun-jit"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
datalove-datafun-ir.path = "../datalove-datafun-ir"
datalove-datafun-interp.path = "../datalove-datafun-interp"
datalove-datafun-aot-cranelift.path = "../datalove-datafun-aot-cranelift"
datalove-rtdt.path = "../datalove-rtdt"
datalove-rt.path = "../datalove-rt"

cranelift-codegen = "0.116"
cranelift-frontend = "0.116"
cranelift-module = "0.116"
cranelift-jit = "0.116"
target-lexicon = "0.13"

[dev-dependencies]
datalove-datafun.path = "../datalove-datafun"

[features]
index-64 = [
    "datalove-datafun-ir/index-64",
    "datalove-datafun-interp/index-64",
    "datalove-datafun-aot-cranelift/index-64",
    "datalove-rtdt/index-64",
    "datalove-rt/index-64",
]
