[package]
name = "datalove-datafun-lower"
description = "Lowering datafun syntax to SSA IR."
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[features]
index-64 = [
    "datalove-rtdt/index-64",
    "datalove-datafun-ir/index-64",
    "datalove-datafun-common/index-64",
    "datalove-datafun-intrinsics/index-64",
    "datalove-datafun-sema/index-64",
]

[dependencies]
rmx.workspace = true
salsa.workspace = true
bct.workspace = true
datalove-datalit.workspace = true
datalove-datafun-ast.workspace = true
datalove-datafun-common.workspace = true
datalove-datafun-intrinsics.workspace = true
datalove-datafun-ir.workspace = true
datalove-datafun-sema.workspace = true
datalove-rtdt.workspace = true
