[package]
name = "datalove-datafun-lower"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[features]
index-64 = [
    "datalove-rtdt/index-64",
    "datalove-datafun-ir/index-64",
    "datalove-datafun-common/index-64",
    "datalove-datafun-intrinsics/index-64",
    "datalove-datafun-sema/index-64",
]

[dependencies]
rmx.workspace = true
salsa.workspace = true
bct.workspace = true
datalove-datalit.path = "../datalove-datalit"
datalove-datafun-ast.path = "../datalove-datafun-ast"
datalove-datafun-common.path = "../datalove-datafun-common"
datalove-datafun-intrinsics.path = "../datalove-datafun-intrinsics"
datalove-datafun-ir.path = "../datalove-datafun-ir"
datalove-datafun-sema.path = "../datalove-datafun-sema"
datalove-rtdt.path = "../datalove-rtdt"
