[package]
name = "datalove-datafun-pkg"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
bct.workspace = true
salsa.workspace = true

[dev-dependencies]
datalove-datafun.path = "../datalove-datafun"
datalove-exampletest.path = "../datalove-exampletest"
