[package]
name = "datalove-datafun-aot-cranelift"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
datalove-datafun-ir.path = "../datalove-datafun-ir"
datalove-rtdt.path = "../datalove-rtdt"
datalove-rt.path = "../datalove-rt"

cranelift-codegen = "0.116"
cranelift-frontend = "0.116"
cranelift-module = "0.116"
cranelift-object = "0.116"
target-lexicon = "0.13"

[dev-dependencies]
tempfile = "3"
datalove-datafun.path = "../datalove-datafun"
