[package]
name = "datalove-datafun-compiler"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[features]
slow_tests = []

[dependencies]
rmx.workspace = true
bct.workspace = true
salsa.workspace = true
serde = { version = "1", features = ["derive"] }
ron = "0.8"
datalove-datafun-ast.path = "../datalove-datafun-ast"
datalove-datafun-ir.path = "../datalove-datafun-ir"
datalove-datafun-parser.path = "../datalove-datafun-parser"
datalove-datafun-tycheck.path = "../datalove-datafun-tycheck"
datalove-datafun-interp.path = "../datalove-datafun-interp"
datalove-datalit.path = "../datalove-datalit"
datalove-diagnostic.path = "../datalove-diagnostic"
datalove-rt.path = "../datalove-rt"
datalove-rtdt.path = "../datalove-rtdt"

[dev-dependencies]
datalove-exampletest.path = "../datalove-exampletest"
rand = "0.8"

[[test]]
name = "parser_tests"
path = "tests/parser_tests.rs"
harness = false

[[test]]
name = "tycheck_tests"
path = "tests/tycheck_tests.rs"
harness = false

