[package]
name = "datalove-datafun-compiler"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[features]
slow_tests = []
index-64 = [
    "datalove-rtdt/index-64",
    "datalove-datafun-common/index-64",
    "datalove-datafun-const/index-64",
    "datalove-datafun-ir/index-64",
    "datalove-datafun-lower/index-64",
    "datalove-datafun-ownership/index-64",
    "datalove-datafun-sema/index-64",
    "datalove-datafun-tycheck/index-64",
    "datalove-datafun-parser/index-64",
    "datalove-datafun-intrinsics/index-64",
    "datalove-datalit/index-64",
]

[dependencies]
rmx.workspace = true
bct.workspace = true
salsa.workspace = true
rustc-hash.workspace = true
serde = { version = "1", features = ["derive"] }
ron = "0.8"
datalove-ct.path = "../datalove-ct"
datalove-datafun-ast.path = "../datalove-datafun-ast"
datalove-datafun-common.path = "../datalove-datafun-common"
datalove-datafun-const.path = "../datalove-datafun-const"
datalove-datafun-intrinsics.path = "../datalove-datafun-intrinsics"
datalove-datafun-ir.path = "../datalove-datafun-ir"
datalove-datafun-lower.path = "../datalove-datafun-lower"
datalove-datafun-ownership.path = "../datalove-datafun-ownership"
datalove-datafun-parser.path = "../datalove-datafun-parser"
datalove-datafun-resolve.path = "../datalove-datafun-resolve"
datalove-datafun-sema.path = "../datalove-datafun-sema"
datalove-datafun-tycheck.path = "../datalove-datafun-tycheck"
datalove-datalit.path = "../datalove-datalit"
datalove-diagnostic.path = "../datalove-diagnostic"
datalove-rt.path = "../datalove-rt"
datalove-rtdt.path = "../datalove-rtdt"

[dev-dependencies]
datalove-exampletest.path = "../datalove-exampletest"
datalove-datafun.path = "../datalove-datafun"
datalove-datafun-pkg.path = "../datalove-datafun-pkg"
rand = "0.8"

[[test]]
name = "parser_tests"
path = "tests/parser_tests.rs"
harness = false

[[test]]
name = "tycheck_tests"
path = "tests/tycheck_tests.rs"
harness = false

[[test]]
name = "auto_adapt_tests"
path = "tests/auto_adapt_tests.rs"
harness = false

