[package]
name = "datalove-datafun-common"
description = "Type definitions shared across the datafun compiler."
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[features]
index-64 = ["datalove-datalit/index-64"]

[dependencies]
rmx.workspace = true
bct.workspace = true
salsa.workspace = true
datalove-ct.workspace = true
datalove-datafun-ast.workspace = true
datalove-datalit.workspace = true
