[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "echo Building Worker WASM..."]

[build]
target = "worker.html"
release = false
dist = "dist"
public_url = "./"

[watch]
ignore = ["dist"]
