[package]
name = "datalove-datafun-tycheck"
description = "A typechecker for datafun."
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[features]
index-64 = ["datalove-datalit/index-64", "datalove-datafun-common/index-64", "datalove-datafun-sema/index-64", "datalove-datafun-resolve/index-64"]

[dependencies]
rmx.workspace = true
bct.workspace = true
salsa.workspace = true
datalove-ct.workspace = true
datalove-datafun-ast.workspace = true
datalove-datafun-common.workspace = true
datalove-datafun-intrinsics.workspace = true
datalove-datafun-parser.workspace = true
datalove-datafun-resolve.workspace = true
datalove-datafun-sema.workspace = true
datalove-datalit.workspace = true
datalove-diagnostic.workspace = true

