[package]
name = "datalove-native-component"
description = "The datalove runtime and native riders, as one linkable library."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
datalove-rt.path = "../datalove-rt"
datalove-rider-std.path = "../../sys/std/rider"
