[package]
name = "datalove-datafun-interp"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[features]
index-64 = ["datalove-rtdt/index-64", "datalove-datafun-ir/index-64"]

[dependencies]
rmx.workspace = true
datalove-datafun-intrinsics.path = "../datalove-datafun-intrinsics"
datalove-datafun-ir.path = "../datalove-datafun-ir"
datalove-rt.path = "../datalove-rt"
datalove-rtdt.path = "../datalove-rtdt"
