[package]
name = "datalove-datafun-parser"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[features]
index-64 = ["datalove-datalit/index-64"]

[dependencies]
rmx.workspace = true
bct.workspace = true
salsa.workspace = true
datalove-datafun-ast.path = "../datalove-datafun-ast"
datalove-datalit.path = "../datalove-datalit"
datalove-diagnostic.path = "../datalove-diagnostic"
