[package]
name = "datalove-rt"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib", "cdylib"]

[features]
slow_tests = []

[dependencies]
rmx.workspace = true
datalove-rtdt.path = "../datalove-rtdt"
libc = "0.2"
backtrace = "0.3"

[dev-dependencies]
proptest = "1.5"
