[package]
name = "datalove-rt-tests"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[features]
slow_tests = []
index-64 = ["datalove-rt/index-64", "datalove-rtdt/index-64", "datalove-datalit/index-64"]

[dependencies]
rmx.workspace = true
bct.workspace = true
salsa.workspace = true
proptest = "1.5"
datalove-rt.path = "../datalove-rt"
datalove-rtdt.path = "../datalove-rtdt"
datalove-datalit.path = "../datalove-datalit"
datalove-exampletest.path = "../datalove-exampletest"

[[test]]
name = "roundtrip_tests"
path = "tests/roundtrip_tests.rs"
harness = false
