#!/usr/bin/env python3
"""Generate the runtime interface declarations from the runtime's definitions.

`crates/datalove-rt/src/c.rs` defines every `dtlv_rti_*` function the ABI
exports. `crates/datalove-rti/src/decl.rs` declares the same functions for
callers that link a runtime rather than containing one, and
`crates/datalove-rt/src/abi_check.rs` makes a disagreement between the two a
compile error.

Run from the repository root:

    uv run --no-project scripts/gen-rti.py
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "crates" / "datalove-rt" / "src" / "c.rs"
DECL = ROOT / "crates" / "datalove-rti" / "src" / "decl.rs"
CHECK = ROOT / "crates" / "datalove-rt" / "src" / "abi_check.rs"

MARKER = "#[unsafe(no_mangle)]"
SIGNATURE = re.compile(r"pub\s+(unsafe\s+)?extern\s+\"C-unwind\"\s+fn\s+(\w+)\s*\(")


def signatures(source):
    """Every exported function, as (name, is_unsafe, params, return type)."""
    lines = source.splitlines()
    for index, line in enumerate(lines):
        if line.strip() != MARKER:
            continue

        # The signature runs from the `fn` to the brace that opens its body,
        # over however many lines the parameters take.
        text = "\n".join(lines[index + 1:])
        match = SIGNATURE.search(text)
        if not match or match.start() > text.find("\n") + 1:
            sys.exit(f"{SOURCE}:{index + 1}: no signature follows {MARKER}")

        depth = 1
        position = match.end()
        while depth:
            if text[position] == "(":
                depth += 1
            elif text[position] == ")":
                depth -= 1
            position += 1

        params = text[match.end():position - 1]
        rest = text[position:text.index("{", position)].strip()
        returns = rest[2:].strip() if rest.startswith("->") else None

        yield match.group(2), bool(match.group(1)), params, returns


def declaration(name, is_unsafe, params, returns):
    """One line of an extern block, with the parameters run together."""
    # A comment explaining an argument is written for whoever reads the
    # definition; running the parameters onto one line would carry it into the
    # rest of them, so it is dropped rather than moved.
    stripped = (re.sub(r"//.*$", "", part).strip() for part in params.split("\n"))

    # A leading underscore says a definition ignores an argument, which is no
    # business of a declaration.
    flat = " ".join(part for part in stripped if part)
    flat = re.sub(r"\b_(\w+)\s*:", r"\1:", flat).rstrip(",")
    flat = re.sub(r"\s+", " ", flat)

    keyword = "fn" if is_unsafe else "safe fn"
    arrow = f" -> {returns}" if returns else ""
    return f"    pub {keyword} {name}({flat}){arrow};"


def main():
    source = SOURCE.read_text()
    found = list(signatures(source))
    exported = source.count(MARKER)
    if len(found) != exported:
        sys.exit(f"parsed {len(found)} signatures but {exported} are exported")

    decls = "\n".join(declaration(*entry) for entry in found)
    DECL.write_text(f'''//! Declarations of the runtime functions a rider calls.
//!
//! Generated from `datalove-rt`'s `c.rs` by `scripts/gen-rti.py`. Do not edit;
//! `datalove-rt`'s `abi_check` module makes a declaration that disagrees with
//! its definition a compile error, and the count below makes an undeclared
//! export one.
//!
//! Nothing here is defined. A caller that links these resolves them against
//! whichever runtime it is loaded into.

use datalove_rtdt as rtdt;

use crate::{{DebugOutputMode, LocalRtHandle, RtEq, RtOrdering, RtStatus}};

/// How many functions the runtime exports.
pub const EXPORTED: usize = {len(found)};

unsafe extern "C-unwind" {{
{decls}
}}
''')

    checks = "\n".join(
        f"    let _ = [crate::c::{name}, datalove_rti::decl::{name}];"
        for name, _, _, _ in found
    )
    CHECK.write_text(f'''//! Every exported function must match its declaration in `datalove-rti`.
//!
//! Generated by `scripts/gen-rti.py`. A rider is built against the
//! declarations and run against these definitions, so the two disagreeing is a
//! rider calling a function whose arguments are not what it passed. Nothing
//! about the symbol name says so, which is why it is checked here instead.
//!
//! Each line puts the definition and the declaration in one array, which makes
//! the compiler coerce both to a single function pointer type and reject the
//! pair if their signatures differ.

const _: () = {{
{checks}
}};

/// The declarations must cover every export, not merely agree with the ones
/// they name. `EXPORTED` is generated from the same scan as the lines above.
const _: () = assert!(
    datalove_rti::decl::EXPORTED == {len(found)},
    "datalove-rti declares a different number of functions than datalove-rt exports",
);
''')

    print(f"wrote {len(found)} declarations to {DECL.relative_to(ROOT)}")
    print(f"wrote {len(found)} checks to {CHECK.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
