[package]
name = "datalove-bench"
description = "Benchmarks for datalove."
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[dev-dependencies]
divan = "0.1"
datalove-datafun-compiler.workspace = true
datalove-datafun-resolve.workspace = true
datalove-datafun-tycheck.workspace = true
datalove-datafun.workspace = true
datalove-datafun-cranelift-jit.workspace = true
datalove-datafun-interp.workspace = true
datalove-datafun-ir.workspace = true
datalove-datafun-parser.workspace = true
datalove-sys-packages.workspace = true
bct.workspace = true
salsa.workspace = true
datalove-ct.workspace = true
rmx.workspace = true

[[bench]]
name = "parallel"
harness = false

[[bench]]
name = "incremental"
harness = false

[[bench]]
name = "frontend"
harness = false

[[bench]]
name = "jit"
harness = false

[[bench]]
name = "runtime"
harness = false
