[package]
name = "datalove-bench"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
publish = false

[dev-dependencies]
divan = "0.1"
datalove-datafun-compiler = { path = "../datalove-datafun-compiler" }
datalove-datafun-tycheck = { path = "../datalove-datafun-tycheck" }
datalove-datafun = { path = "../datalove-datafun" }
datalove-datafun-cranelift-jit = { path = "../datalove-datafun-cranelift-jit" }
datalove-datafun-interp = { path = "../datalove-datafun-interp" }
bct.workspace = true

[[bench]]
name = "parallel"
harness = false

[[bench]]
name = "jit"
harness = false
