[package]
name = "datalove-datafun-cranelift-aot"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[features]
index-64 = [
    "datalove-datafun-cranelift/index-64",
    "datalove-datafun-ir/index-64",
]

[dependencies]
rmx.workspace = true
datalove-datafun-cranelift.path = "../datalove-datafun-cranelift"
datalove-datafun-ir.path = "../datalove-datafun-ir"

cranelift-codegen = "0.128"
cranelift-frontend = "0.128"
cranelift-module = "0.128"
cranelift-object = "0.128"
target-lexicon = "0.13"

[dev-dependencies]
datalove-datafun.path = "../datalove-datafun"
