[package]
name = "datalove-datafun-cranelift-aot"
description = "The datafun ahead-of-time Cranelift backend."
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[features]
index-64 = [
    "datalove-datafun-cranelift/index-64",
    "datalove-datafun-ir/index-64",
]

[dependencies]
rmx.workspace = true
datalove-datafun-cranelift.workspace = true
datalove-datafun-ir.workspace = true

cranelift-codegen = "0.135"
cranelift-frontend = "0.135"
cranelift-module = "0.135"
cranelift-object = "0.135"
target-lexicon = "0.13"

[dev-dependencies]
datalove-datafun.path = "../datalove-datafun"
