[package]
name = "datalove-cli"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
serde = { version = "1", features = ["derive"] }
bct.workspace = true
datalove.path = "../datalove"
datalove-datalit.path = "../datalove-datalit"
datalove-datafun.path = "../datalove-datafun"
datalove-datafun-tycheck.path = "../datalove-datafun-tycheck"
datalove-datafun-interp.path = "../datalove-datafun-interp"
datalove-datafun-jit.path = "../datalove-datafun-jit"
datalove-diagnostic.path = "../datalove-diagnostic"
datalove-datafun-parser.path = "../datalove-datafun-parser"
datalove-rt.path = "../datalove-rt"
datalove-repl.path = "../datalove-repl"
datalove-repl-term.path = "../datalove-repl-term"
datalove-datafun-pkg.path = "../datalove-datafun-pkg"
pulldown-cmark = "0.12"
ariadne = "0.4"
salsa.workspace = true

[[bin]]
name = "datalove"
path = "src/main.rs"

[dev-dependencies]
datalove-exampletest.path = "../datalove-exampletest"

[[test]]
name = "script_tests"
path = "tests/script_tests.rs"
harness = false

[[test]]
name = "error_tests"
path = "tests/error_tests.rs"
harness = false

[[test]]
name = "aot_run_tests"
path = "tests/aot_run_tests.rs"
harness = false

[[test]]
name = "world_error_tests"
path = "tests/world_error_tests.rs"
harness = false
