[package]
name = "datalove-cli"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
bct.workspace = true
datalove.path = "../datalove"
datalove-datalit.path = "../datalove-datalit"
datalove-rt.path = "../datalove-rt"
datalove-repl-term.path = "../datalove-repl-term"
clap.version = "4.5"
clap.features = ["derive"]

[[bin]]
name = "datalove"
path = "src/main.rs"
