[package]
name = "datalove-cli"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
bct.workspace = true
datalove.path = "../datalove"
datalove-datalit.path = "../datalove-datalit"
datalove-rt.path = "../datalove-rt"
datalove-repl.path = "../datalove-repl"
datalove-repl-term.path = "../datalove-repl-term"

[[bin]]
name = "datalove"
path = "src/main.rs"

[dev-dependencies]
termcolor = "1.4"
crossterm = "0.28"
ratatui = { version = "0.29", features = ["crossterm"] }
datalove-repl-rat.path = "../datalove-repl-rat"

[[test]]
name = "repl_tests"
path = "tests/repl_tests.rs"
harness = false
