[package]
name = "datalove-worldgen"
description = "A worldfile generator for datafun."
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
rmx.workspace = true
bct.workspace = true
salsa.workspace = true
rand = "0.8"
datalove-datalit.workspace = true
datalove-datafun-ast.workspace = true

[dev-dependencies]
datalove-datafun.path = "../datalove-datafun"
datalove-datafun-parser.path = "../datalove-datafun-parser"
datalove-datafun-pkg.path = "../datalove-datafun-pkg"
datalove-datafun-tycheck.path = "../datalove-datafun-tycheck"
datalove-datafun-resolve.path = "../datalove-datafun-resolve"
