[package]
name = "datalove-worldgen"
description = "A worldfile generator for datafun."
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
rmx.workspace = true
bct.workspace = true
salsa.workspace = true
rand = "0.8"
datalove-datalit.workspace = true
datalove-datafun-ast.workspace = true

[dev-dependencies]
datalove-datafun.workspace = true
datalove-datafun-parser.workspace = true
datalove-datafun-pkg.workspace = true
datalove-datafun-tycheck.workspace = true
datalove-datafun-resolve.workspace = true
