[package]
name = "datalove-datafun-cranelift"
description = "Cranelift codegen shared by the datafun backends."
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[features]
index-64 = [
    "datalove-rtdt/index-64",
    "datalove-datafun-ir/index-64",
    "datalove-datafun-intrinsics/index-64",
]

[dependencies]
rmx.workspace = true
datalove-datafun-intrinsics.workspace = true
datalove-datafun-ir.workspace = true
datalove-rtdt.workspace = true
datalove-rt.workspace = true

cranelift-codegen = "0.135"
cranelift-frontend = "0.135"
cranelift-module = "0.135"

[dev-dependencies]
cranelift-object = "0.135"
target-lexicon = "0.13"
