[package]
name = "datalove-datafun-cranelift-jit"
description = "A per-function tracing JIT for the datafun interpreter."
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
rmx.workspace = true
rustc-hash.workspace = true
datalove-datafun-ir.workspace = true
datalove-datafun-interp.workspace = true
datalove-datafun-cranelift.workspace = true
datalove-rtdt.workspace = true
datalove-rt.workspace = true

cranelift-codegen = "0.135"
cranelift-frontend = "0.135"
cranelift-module = "0.135"
cranelift-jit = "0.135"
target-lexicon = "0.13"

[features]
index-64 = [
    "datalove-datafun-ir/index-64",
    "datalove-datafun-interp/index-64",
    "datalove-datafun-cranelift/index-64",
    "datalove-rtdt/index-64",
    "datalove-rt/index-64",
]
